### ISSUE TITLE
Update design for the Open Ownership Map

### ISSUE THREAD

**Issue by StephenAbbott** [openownership/openownership.org-wagtail#397]
As of August 2023, the [Open Ownership Map](https://www.openownership.org/en/map/) (OO Map) is focused on communicating which countries have committed to a central beneficial ownership register or a public register alongside details about whether those countries have gone on to actually implement said central or public registers.

The focus of the Open Ownership/Hactar tech sprint taking place in September 2023 is to move away from this central/public binary but to still use data from our integrated Notion databases to categorise countries on the OO Map.

The future categories we would like to move to are:
- Planned
- Implementing
- Live register

We would like to take this opportunity to redesign the OO Map page to implement the following design changes as well as retaining a lot of the existing functionality.

The overall aims for this redesign are to change the categories and to make it clear that the OO Map is a gateway to lots of information on countries/regions.

**New functionality requests**

- [x] Remove Commitment to BOT and Implementation of BOT information boxes
- [x] All countries on OO Map labeled and coloured as being at one of three stages: Planned / Implementing / Live register (countries can only be in one category). We can use a different range of colours if desired. The Open Ownership brand guidelines can be downloaded [here](https://openownershiporgprod-1b54.kxcdn.com/media/documents/oo-brand-guidelines-2020-07.pdf). We should bear in mind that the category labels used on the OO Map page should also be shown on the OO country pages (see https://github.com/openownership/openownership.org-wagtail/issues/398)
- [x] On the OO Map page, list the categories with a count next to each category name for the number of countries currently in that category
- [x] Clicking on a category name filters the OO Map to just show countries in that category
- [x] Update ‘Countries where Open Ownership is engaged’ to say ‘Countries where Open Ownership has engaged’
- [x] Make the OO Map page full-width by removing the left-hand navigation bar
- [x] Consider best approach to retain/enhance the 'Find a specific country' functionality below the OO Map
- [x] Once work is complete to design/create 'region' pages (see https://github.com/openownership/openownership.org-wagtail/issues/350), add prominent links from below the OO Map to these region pages for Europe / Asia / South America / North America / Oceania / Africa
- [x] Update the 'NOTE: Country boundaries [source](https://geojson-maps.ash.ms/)' text to make it clear where the OO Map country data is drawn from but revise language or make link less prominent on page
- [x] Add a brief text field for OO team members to explain what the categories on the map mean

**Existing functionality to retain**

- [x] Users can hover over map on desktop to see name and click on country to go to country page. On mobile, retain behaviour where single click on a country takes users to country page
- [x] Zoom functionality should still be available for OO Map (bear in mind recent work - see https://github.com/openownership/openownership.org-wagtail/issues/143 - to make it easier to be able to zoom in on small island nations to click on them)
- [x] Keep note saying 'Data on the Open Ownership map is drawn from publicly-available sources and may not be comprehensive for all countries. If data is incorrect, [please let us know](https://share.hsforms.com/1ooDVGfPWQFyc93l3Bds9jA3upv4)'
- [x] [Download all country data](https://www.openownership.org/en/map/oo_all_country_data.csv) button should be retained

These design changes should be considered alongside plans to 'Update design for Open Ownership country pages' (see https://github.com/openownership/openownership.org-wagtail/issues/398).

**Comment by HollieWilmot** [comment]
Hi @StephenAbbott one quick question on this, can you explain:

Update the 'NOTE: Country boundaries [source](https://geojson-maps.ash.ms/)' text to make it clear where the OO Map country data is drawn from but revise language or make link less prominent on page. 

Could you provide the new text/language for this NOTE?

**Comment by StephenAbbott** [comment]
Sure @HollieWilmot. Please could we use text saying 'Country boundaries data is taken from [NaturalEarth](https://geojson-maps.ash.ms/)' and hope that we can place this text somewhere less prominent on the OO Map page

**Comment by HollieWilmot** [comment]
@StephenAbbott fyi 

Internal testing feedback: 

Can we update the map image on this page: https://openownership.hactar.work/en/impact/ to reflect the new map design. 

**Map Page** 
- The space above the title looks a bit taller than other pages by comparison.  Please reduce the padding. 
- Can we add a white key line to the pink spot in the key as per those on the map.  
- As there’s a line at the bottom of the accordion, we can lose the extra horizontal line here. 
- Change: NOTE: Country boundaries source to: 'Country boundaries data is taken from NaturalEarth'

**Comment by StephenAbbott** [comment]
@HollieWilmot I've updated the promo image for the OO Map which was displaying on the following pages:
https://openownership.hactar.work/en/
https://openownership.hactar.work/en/impact/

**Comment by StephenAbbott** [comment]
@HollieWilmot Small change requested to categories explainer text on OO Map.

Please change to the following:

Once a country makes at least a commitment to beneficial ownership transparency, it will be labelled as Planned. After work starts on implementing a register, it will be labelled as Implementing. Following the launch of one or more beneficial ownership registers, the country will be labelled as Live register.

For some reason, I wrote "they" in the first sentence when sending the text through before 🙄

**Comment by HollieWilmot** [comment]
Morning @StephenAbbott 

The map page is now updated and ready for you to review: https://openownership.hactar.work/en/map/

**Comment by StephenAbbott** [comment]
Thanks @HollieWilmot. Looks good. Happy with this

**Comment by HollieWilmot** [comment]
The map colours have now been updated for greater contrast.

Planned = 'Systems' Blue
implementing = 'Commit' Purple
Live = 'Data' Green

https://openownership.hactar.work/en/map/

**Comment by StephenAbbott** [comment]
Signed off ✅
